-- ==========================================================
-- STORAGE LOCKDOWN: id-photos (GOVERNMENT ID PHOTOS)
-- Created 2026-08-01. APPLIED — verified 2026-08-03: the id-photos bucket exists
-- with public = false, and all three policies below are present on
-- storage.objects. Re-running is safe; the bucket INSERT re-asserts public =
-- false on conflict, which is the point of writing it that way.
-- ==========================================================
--
-- This bucket holds photographs of driving licences and passports belonging to
-- named people whose addresses are already public in the DBPR registry. It is
-- the single most sensitive store in the project. A leak here is an identity
-- theft kit, not an embarrassment.
--
-- Four independent things must all hold for a photo to stay private:
--
--   1. the bucket is private, so there is no public URL to guess
--   2. RLS on storage.objects restricts every path to its owning user
--   3. reads happen through short-lived signed URLs, minted server-side
--   4. the row in public.claims stores a PATH, never a URL
--
-- Any one of them failing is survivable. That is the point of having four.
-- ==========================================================


-- ==========================================================
-- 1. THE BUCKET
-- ==========================================================
--
-- public = false is the whole ballgame. In a public bucket every object is
-- readable at a guessable URL by anyone on the internet, RLS is not consulted
-- at all, and no amount of correct policy below would matter.
--
-- file_size_limit 10 MB: a modern phone camera produces 3-8 MB for a document
-- photo, and HEIC from an iPhone can exceed 8. Set lower and real contractors
-- silently fail at the one step we need them to complete.
--
-- allowed_mime_types deliberately EXCLUDES image/svg+xml. SVG is a script
-- carrier, not a photograph — nobody photographs an ID into an SVG, and if one
-- is ever rendered inline it executes. There is no upside to allowing it.
--
-- ⚠ allowed_mime_types is checked against the Content-Type the CLIENT sends.
-- It is a guardrail against mistakes, NOT a proof of file contents. Treat every
-- object here as untrusted bytes: never render one inline, never pass one to an
-- image processor that parses metadata, always serve as an attachment.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'id-photos',
  'id-photos',
  false,
  10485760,  -- 10 MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
ON CONFLICT (id) DO UPDATE
  SET public             = false,   -- re-assert on every run: this must never drift
      file_size_limit    = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;


-- ==========================================================
-- 2. PATH STRUCTURE  →  {claimant_user_id}/{claim_id}.{ext}
-- ==========================================================
--
-- The first segment is the user's auth.uid(). That is what every policy below
-- tests, so the path is not a naming convention — it IS the access control.
--
-- claim_id is generated by the application BEFORE the upload (a client-side
-- uuid), then used as the primary key of the claims row. Generating it up front
-- is what lets the file and the row share an identifier without a round trip.
--
-- A fresh uuid PER ATTEMPT, not per claim: policies below forbid overwriting,
-- so a retry after a half-failed upload must not reuse the old id or it will
-- collide and fail forever.


-- ==========================================================
-- 3. RLS ON storage.objects
-- ==========================================================
--
-- Supabase enables RLS on storage.objects by default; asserted here because
-- every policy below is worthless without it.
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- ---------- anon: NOTHING ----------
-- There is deliberately no policy granting anon anything on this bucket.
-- Under RLS, absence of a policy is a denial — so this is enforced, not merely
-- unmentioned. Do not add one "for the upload page"; uploads are authenticated.

-- ---------- contractor: INSERT into own folder only ----------
CREATE POLICY "claimant uploads own id photo"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'id-photos'
    -- First path segment must be the caller's own uid. This is the isolation.
    AND (storage.foldername(name))[1] = auth.uid()::text
    -- Exactly one folder level: forbids "me/../someone-else" style nesting and
    -- keeps the path shape the review query below depends on.
    AND array_length(storage.foldername(name), 1) = 1
  );

-- ---------- contractor: SELECT own folder only ----------
CREATE POLICY "claimant reads own id photo"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'id-photos'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- ---------- NO UPDATE, NO DELETE for contractors. INTENTIONAL. ----------
--
-- Not an oversight, and not tidiness. An ID photo is evidence in a manual
-- review. If the claimant could UPDATE the object they could let Jim approve a
-- genuine licence and then swap the bytes afterwards, leaving an approved claim
-- backed by a file nobody ever reviewed — with no trace, because the path and
-- the row are unchanged.
--
-- DELETE is withheld for the same reason: an approved claim whose evidence has
-- been erased by the person it approved cannot be audited later.
--
-- The cost is that a contractor cannot retract a photo themselves. That is a
-- support request, and it is the correct trade for a verification record.

-- ---------- admin: full access ----------
CREATE POLICY "admin full access id photos"
  ON storage.objects FOR ALL
  TO authenticated
  USING (bucket_id = 'id-photos' AND is_admin())
  WITH CHECK (bucket_id = 'id-photos' AND is_admin());
-- is_admin() reads app_metadata ONLY. See 20260801_fix_is_admin.sql — when it
-- also trusted user_metadata, any signed-up visitor could have satisfied this.


-- ==========================================================
-- 4. THE claims.id_photo_url COLUMN IS A PATH, NOT A URL
-- ==========================================================
--
-- The column is named id_photo_url and that name is a trap: it invites storing
-- a public URL, and a public URL to this bucket is the one thing that undoes
-- everything above. Store the storage path — 'a1b2.../c3d4....jpg' — and mint a
-- signed URL at the moment of viewing.
--
-- Renaming the column is the honest fix; left for a migration that can update
-- the application in the same change.
COMMENT ON COLUMN public.claims.id_photo_url IS
  'STORAGE PATH inside the private id-photos bucket ({user_id}/{claim_id}.ext) - NOT a URL. Never store a public URL here; the bucket is private and reads go through short-lived signed URLs.';


-- ==========================================================
-- 5. HOW JIM REVIEWS — ⚠ SUPERSEDED. DO NOT FOLLOW THIS SECTION.
-- ==========================================================
--
-- SUPERSEDED by 20260801_claim_decision_functions.sql, which replaced the
-- two-statement approval with approve_claim()/reject_claim(), and by the admin
-- UI at /admin/claims. Reviewing now means opening that page, not the SQL
-- editor. Same note as the one on public.claims in 20260801_claims_flow.sql.
--
-- The hand-written UPDATEs below are the exact hazard approve_claim() exists to
-- remove: they are two statements, and running the first without the second
-- leaves a claim reading "approved" while contractors.claimed_by_user_id is
-- still null — an approval that grants nothing. The ⚠ at the end of this
-- section asks for a trigger "once the admin UI exists". That question is
-- answered; the function is the answer.
--
-- They are also now incomplete in a way that is easy to miss. Both RPCs re-base
-- id_photo_expires_at to the DECISION date, which is the retention promise the
-- claims table makes. An UPDATE typed by hand skips that, leaving the photo on
-- the submission clock and the row quietly disagreeing with the stated policy.
--
-- Kept rather than deleted because the queue query and the "how to see the
-- photo" note below are still the right way to inspect the bucket by hand, and
-- because what the process used to be is worth being able to read.
--
-- Pending queue — run in the SQL editor:
--
--   SELECT c.id, c.created_at, c.claimant_name, c.claimant_email,
--          c.contractor_dbpr_sync_key, k.business_name, c.id_photo_url AS storage_path
--     FROM claims c
--     LEFT JOIN contractors k ON k.dbpr_sync_key = c.contractor_dbpr_sync_key
--    WHERE c.status = 'pending'
--    ORDER BY c.created_at;
--
-- To see the photo: Storage → id-photos → open the folder named for the
-- claimant's user id → click the file. The dashboard authenticates as the
-- service role, so this works without an admin UI and without making anything
-- public.
--
-- To approve:
--   UPDATE claims SET status='approved', reviewed_at=now(),
--          reviewed_by_user_id='<jim-uid>'
--    WHERE id='<claim-id>';
--   UPDATE contractors SET claimed_by_user_id='<claimant-uid>'
--    WHERE dbpr_sync_key='<key>';
--
-- To reject:
--   UPDATE claims SET status='rejected', reviewed_at=now(),
--          reviewed_by_user_id='<jim-uid>', rejection_reason='<why>'
--    WHERE id='<claim-id>';
--
-- ⚠ The two approve statements must both run. A claims row marked approved
-- while contractors.claimed_by_user_id is still null is an approval that grants
-- nothing — the contractor signs in, sees no profile, and reports a bug that
-- looks like auth. Worth a trigger once the admin UI exists.


-- ==========================================================
-- 6. ⚠ THE 90-DAY DELETION IS NOT IMPLEMENTED
-- ==========================================================
--
-- public.claims is commented "ID photos auto-delete 90 days post-decision" and
-- id_photo_expires_at is NOT NULL, so every row will carry a deletion promise.
-- NOTHING CURRENTLY DELETES ANYTHING. As written, that comment is a claim we do
-- not keep, and if it reaches a privacy policy it becomes a false statement
-- about PII handling.
--
-- Deliberately not solved in this migration: it needs pg_cron (or a scheduled
-- route) plus a decision about whether the row survives the photo. Flagged so
-- it is a decision rather than an oversight. Sketch:
--
--   SELECT cron.schedule('purge-expired-id-photos', '0 3 * * *', $$
--     ... delete from storage.objects where bucket_id='id-photos'
--         and name in (select id_photo_url from claims
--                       where id_photo_expires_at < now()) ...
--   $$);


-- ==========================================================
-- 7. VERIFY — run all of these after applying
-- ==========================================================
--
-- Bucket is private:
--   SELECT id, public FROM storage.buckets WHERE id='id-photos';   -- public = false
--
-- Policies exist and anon has none:
--   SELECT polname FROM pg_policy p JOIN pg_class c ON c.oid=p.polrelid
--    WHERE c.relname='objects';
--
-- NEGATIVE TESTS — these are the ones that matter, and an empty bucket proves
-- nothing. Upload one throwaway file first, then:
--
--   a) anon (public anon key, no session):
--        storage.from('id-photos').list('')        -> [] / error, never the file
--        storage.from('id-photos').download(path)  -> error
--        GET /storage/v1/object/public/id-photos/<path> -> 400/404
--   b) contractor B signed in, requesting contractor A's path:
--        download('<A-uid>/<claim>.jpg')           -> error
--   c) contractor A, own path:                     -> succeeds
--   d) contractor A attempting to overwrite own file (update/upsert)
--                                                  -> DENIED (no UPDATE policy)
-- ==========================================================
